### PR TITLE
feat: add venue section

### PR DESCRIPTION
**Pull request by LBBO**
Adds a venue section to the website. The build is expected to fail until @jfcurran has added the map image.

### CODE REVIEW

**Comment by LBBO** [comment]
@jfcurran, any updates on the map?

**Comment by jfcurran** [comment]
Please don't create additional dependencies @LBBO - the map is part of the design file in figma, and while I appreciate dynamically coloring a png, If the PR is held back for 2 days because of it then its probably not the best. Creating a clean svg from google map is not trivial and cleaning the png will result in poorly pixelated images. Please use the two files I exported, for light and dark

**Comment by LBBO** [comment]
I didn't do this for fun or because I liked the code, I did it for page speed, SEO etc. because this allows us to statically serve one image that can be loaded instantly (or even inlined) versus having to do a round trip to load a script, determine the theme, and then load the image.

Also, you said that you wanted to export a new map anyways so this looked like a plus to me, allowing you to only do it once instead of twice. It seems like you no longer plan on exporting the new map, right? Is there any reason why I can't just take the PNG and modify it in GIMP to fit my needs?

**Comment by jfcurran** [comment]
transparent map added, not as good as an svg

**Review by OryTiki — CHANGES_REQUESTED** [review]
Please open the link to google maps in a new window
There is no target set for google (so I don't get a Pin)

**Comment by LBBO** [comment]
Don't merge yet

**Pull request merged**
