### PR TITLE
feat: add redirects for general 404 and about

### PR DESCRIPTION
**Pull request by LBBO**
Adds an anchor to about section to redirect to from `/about`. Also redirects all other URLs to `/` to handle potential old backlinks. Also, once the venue section is added, a redirect will be added for that as well.

### CODE REVIEW

**Review by aeneasr — CHANGES_REQUESTED** [review]
Please use vercel redirects, javascript redirects are not caught by google!

https://vercel.com/docs/concepts/edge-network/redirects

**Comment by LBBO** [comment]
This is an SSR redirect, so it should be caught. I'd kind of prefer to have this kind of infrastructure be reflected in code in order to avoid confusion, but if you're worried about speed (or there's another reason this wouldn't work), I can set it up anyway

**Comment by aeneasr** [comment]
Please define redirects the way we define them for all other pages:

- https://github.com/ory/docs/blob/master/vercel.json
- https://github.com/ory-corp/web/blob/master/static/_redirects

Adding code pages for redirects is (a) a lot more code (b) harder to keep track of (c) harder to migrate to another system and (d) you can't define the response code.

**Comment by LBBO** [comment]
Done. I added redirects to some anchors that don't exist yet but will soon (e.g. venue is already being worked on). Afaik, this isn't an issue as some frameworks use inexistent anchors for navigation, but I might be misinformed. Just lmk

**Pull request merged**
